### ISSUE TITLE
Allow or and other operators in search

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-site#433] opened 2023-07-31 19:05 UTC
It would be nice to allow operators in the search bar. For example, using "or" to see combos that contain any of the listed properties. For example, the query: `card:"freed from the real" or card:"pemmin's aura"` would return any combo that contains _either_ Freed from the Real or Pemmin's Aura. This is useful when searching for interchangeable cards, like Freed from the Real and Pemmin's Aura. The exact operators can be changed as needed to not conflict with card names and such.

![image](https://github.com/SpaceCowMedia/commander-spellbook-site/assets/97813519/feb50eba-7613-4fee-803c-38a3376cfb8f)

**Comment by ldeluigi** [comment] 2023-08-30 08:02
Duplicate of #105

**Closed by ldeluigi** 2023-08-30 08:02 UTC
Labels: enhancement, proposal
